# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e7e0eb"

# Title color for boxes
theme[title]="#85d7ae"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e0bbdd"

# Background color of selected item in processes box
theme[selected_bg]="#85d7ae"

# Foreground color of selected item in processes box
theme[selected_fg]="#003824"

# Color of inactive/disabled text
theme[inactive_fg]="#cbc3d5"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d3bdf5"

# Cpu box outline color
theme[cpu_box]="#948e9f"

# Memory/disks box outline color
theme[mem_box]="#948e9f"

# Net up/down box outline color
theme[net_box]="#948e9f"

# Processes box outline color
theme[proc_box]="#948e9f"

# Box divider line and small boxes line color
theme[div_line]="#494453"

# Temperature graph colors
theme[temp_start]="#e0bbdd"
theme[temp_mid]="#85d7ae"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e0bbdd"
theme[cpu_mid]="#85d7ae"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e0bbdd"
theme[free_mid]=""
theme[free_end]="#593d59"

# Mem/Disk cached meter
theme[cached_start]="#d3bdf5"
theme[cached_mid]=""
theme[cached_end]="#503e6d"

# Mem/Disk available meter
theme[available_start]="#85d7ae"
theme[available_mid]=""
theme[available_end]="#005236"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e0bbdd"
theme[download_mid]="#85d7ae"
theme[download_end]="#d3bdf5"

# Upload graph colors
theme[upload_start]="#e0bbdd"
theme[upload_mid]="#85d7ae"
theme[upload_end]="#d3bdf5"
