# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#efe0d5"

# Title color for boxes
theme[title]="#feb876"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e2c0a4"

# Background color of selected item in processes box
theme[selected_bg]="#feb876"

# Foreground color of selected item in processes box
theme[selected_fg]="#4b2800"

# Color of inactive/disabled text
theme[inactive_fg]="#d5c3b6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c1cc99"

# Cpu box outline color
theme[cpu_box]="#9e8e81"

# Memory/disks box outline color
theme[mem_box]="#9e8e81"

# Net up/down box outline color
theme[net_box]="#9e8e81"

# Processes box outline color
theme[proc_box]="#9e8e81"

# Box divider line and small boxes line color
theme[div_line]="#51443a"

# Temperature graph colors
theme[temp_start]="#e2c0a4"
theme[temp_mid]="#feb876"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e2c0a4"
theme[cpu_mid]="#feb876"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e2c0a4"
theme[free_mid]=""
theme[free_end]="#59422d"

# Mem/Disk cached meter
theme[cached_start]="#c1cc99"
theme[cached_mid]=""
theme[cached_end]="#424b23"

# Mem/Disk available meter
theme[available_start]="#feb876"
theme[available_mid]=""
theme[available_end]="#6a3b01"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e2c0a4"
theme[download_mid]="#feb876"
theme[download_end]="#c1cc99"

# Upload graph colors
theme[upload_start]="#e2c0a4"
theme[upload_mid]="#feb876"
theme[upload_end]="#c1cc99"
