# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e8e0e7"

# Title color for boxes
theme[title]="#dfb7ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d5bee3"

# Background color of selected item in processes box
theme[selected_bg]="#dfb7ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#441c65"

# Color of inactive/disabled text
theme[inactive_fg]="#cec3d0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ffb0c9"

# Cpu box outline color
theme[cpu_box]="#978e9a"

# Memory/disks box outline color
theme[mem_box]="#978e9a"

# Net up/down box outline color
theme[net_box]="#978e9a"

# Processes box outline color
theme[proc_box]="#978e9a"

# Box divider line and small boxes line color
theme[div_line]="#4b444f"

# Temperature graph colors
theme[temp_start]="#d5bee3"
theme[temp_mid]="#dfb7ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d5bee3"
theme[cpu_mid]="#dfb7ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d5bee3"
theme[free_mid]=""
theme[free_end]="#534261"

# Mem/Disk cached meter
theme[cached_start]="#ffb0c9"
theme[cached_mid]=""
theme[cached_end]="#b05778"

# Mem/Disk available meter
theme[available_start]="#dfb7ff"
theme[available_mid]=""
theme[available_end]="#8c62af"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d5bee3"
theme[download_mid]="#dfb7ff"
theme[download_end]="#ffb0c9"

# Upload graph colors
theme[upload_start]="#d5bee3"
theme[upload_mid]="#dfb7ff"
theme[upload_end]="#ffb0c9"
