
$image = Null
$background = rgba(15121aff)

$image = Null
$error = rgba(ffb4abff)

$image = Null
$error_container = rgba(93000aff)

$image = Null
$inverse_on_surface = rgba(322f37ff)

$image = Null
$inverse_primary = rgba(0e6c4aff)

$image = Null
$inverse_surface = rgba(e7e0ebff)

$image = Null
$on_background = rgba(e7e0ebff)

$image = Null
$on_error = rgba(690005ff)

$image = Null
$on_error_container = rgba(ffdad6ff)

$image = Null
$on_primary = rgba(003824ff)

$image = Null
$on_primary_container = rgba(a1f4c9ff)

$image = Null
$on_primary_fixed = rgba(002113ff)

$image = Null
$on_primary_fixed_variant = rgba(005236ff)

$image = Null
$on_secondary = rgba(412742ff)

$image = Null
$on_secondary_container = rgba(fed7faff)

$image = Null
$on_secondary_fixed = rgba(2a122cff)

$image = Null
$on_secondary_fixed_variant = rgba(593d59ff)

$image = Null
$on_surface = rgba(e7e0ebff)

$image = Null
$on_surface_variant = rgba(cbc3d5ff)

$image = Null
$on_tertiary = rgba(392755ff)

$image = Null
$on_tertiary_container = rgba(ecdcffff)

$image = Null
$on_tertiary_fixed = rgba(23113fff)

$image = Null
$on_tertiary_fixed_variant = rgba(503e6dff)

$image = Null
$outline = rgba(948e9fff)

$image = Null
$outline_variant = rgba(494453ff)

$image = Null
$primary = rgba(85d7aeff)

$image = Null
$primary_container = rgba(005236ff)

$image = Null
$primary_fixed = rgba(a1f4c9ff)

$image = Null
$primary_fixed_dim = rgba(85d7aeff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(e0bbddff)

$image = Null
$secondary_container = rgba(593d59ff)

$image = Null
$secondary_fixed = rgba(fed7faff)

$image = Null
$secondary_fixed_dim = rgba(e0bbddff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(191a3cff)

$image = Null
$surface = rgba(15121aff)

$image = Null
$surface_bright = rgba(3b3840ff)

$image = Null
$surface_container = rgba(211e26ff)

$image = Null
$surface_container_high = rgba(2b2931ff)

$image = Null
$surface_container_highest = rgba(36333cff)

$image = Null
$surface_container_low = rgba(1d1a22ff)

$image = Null
$surface_container_lowest = rgba(0f0d14ff)

$image = Null
$surface_dim = rgba(15121aff)

$image = Null
$surface_tint = rgba(85d7aeff)

$image = Null
$surface_variant = rgba(494453ff)

$image = Null
$tertiary = rgba(d3bdf5ff)

$image = Null
$tertiary_container = rgba(503e6dff)

$image = Null
$tertiary_fixed = rgba(ecdcffff)

$image = Null
$tertiary_fixed_dim = rgba(d3bdf5ff)

