
$image = Null
$background = rgba(161219ff)

$image = Null
$error = rgba(ffb4abff)

$image = Null
$error_container = rgba(93000aff)

$image = Null
$inverse_on_surface = rgba(332f37ff)

$image = Null
$inverse_primary = rgba(006b55ff)

$image = Null
$inverse_surface = rgba(e9e0ebff)

$image = Null
$on_background = rgba(e9e0ebff)

$image = Null
$on_error = rgba(690005ff)

$image = Null
$on_error_container = rgba(ffdad6ff)

$image = Null
$on_primary = rgba(00382bff)

$image = Null
$on_primary_container = rgba(98f4d6ff)

$image = Null
$on_primary_fixed = rgba(002018ff)

$image = Null
$on_primary_fixed_variant = rgba(005140ff)

$image = Null
$on_secondary = rgba(45263dff)

$image = Null
$on_secondary_container = rgba(ffd7f0ff)

$image = Null
$on_secondary_fixed = rgba(2d1227ff)

$image = Null
$on_secondary_fixed_variant = rgba(5d3c54ff)

$image = Null
$on_surface = rgba(e9e0ebff)

$image = Null
$on_surface_variant = rgba(cec3d4ff)

$image = Null
$on_tertiary = rgba(3f2551ff)

$image = Null
$on_tertiary_container = rgba(f3daffff)

$image = Null
$on_tertiary_fixed = rgba(290f3bff)

$image = Null
$on_tertiary_fixed_variant = rgba(573c69ff)

$image = Null
$outline = rgba(978d9dff)

$image = Null
$outline_variant = rgba(4c4452ff)

$image = Null
$primary = rgba(7cd7bbff)

$image = Null
$primary_container = rgba(005140ff)

$image = Null
$primary_fixed = rgba(98f4d6ff)

$image = Null
$primary_fixed_dim = rgba(7cd7bbff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(e6bad7ff)

$image = Null
$secondary_container = rgba(5d3c54ff)

$image = Null
$secondary_fixed = rgba(ffd7f0ff)

$image = Null
$secondary_fixed_dim = rgba(e6bad7ff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(736b96ff)

$image = Null
$surface = rgba(161219ff)

$image = Null
$surface_bright = rgba(3c3740ff)

$image = Null
$surface_container = rgba(221e26ff)

$image = Null
$surface_container_high = rgba(2d2830ff)

$image = Null
$surface_container_highest = rgba(38333bff)

$image = Null
$surface_container_low = rgba(1e1a22ff)

$image = Null
$surface_container_lowest = rgba(100d14ff)

$image = Null
$surface_dim = rgba(161219ff)

$image = Null
$surface_tint = rgba(7cd7bbff)

$image = Null
$surface_variant = rgba(4c4452ff)

$image = Null
$tertiary = rgba(dcbaf0ff)

$image = Null
$tertiary_container = rgba(573c69ff)

$image = Null
$tertiary_fixed = rgba(f3daffff)

$image = Null
$tertiary_fixed_dim = rgba(dcbaf0ff)

