
$image = Null
$background = rgba(171216ff)

$image = Null
$error = rgba(ffb4abff)

$image = Null
$error_container = rgba(93000aff)

$image = Null
$inverse_on_surface = rgba(352e33ff)

$image = Null
$inverse_primary = rgba(804d78ff)

$image = Null
$inverse_surface = rgba(ecdfe5ff)

$image = Null
$on_background = rgba(ecdfe5ff)

$image = Null
$on_error = rgba(690005ff)

$image = Null
$on_error_container = rgba(ffdad6ff)

$image = Null
$on_primary = rgba(4c1f48ff)

$image = Null
$on_primary_container = rgba(ffd7f4ff)

$image = Null
$on_primary_fixed = rgba(340831ff)

$image = Null
$on_primary_fixed_variant = rgba(663560ff)

$image = Null
$on_secondary = rgba(3d2b39ff)

$image = Null
$on_secondary_container = rgba(f8daeeff)

$image = Null
$on_secondary_fixed = rgba(271624ff)

$image = Null
$on_secondary_fixed_variant = rgba(554050ff)

$image = Null
$on_surface = rgba(ecdfe5ff)

$image = Null
$on_surface_variant = rgba(d1c2cbff)

$image = Null
$on_tertiary = rgba(4c261aff)

$image = Null
$on_tertiary_container = rgba(ffdbd0ff)

$image = Null
$on_tertiary_fixed = rgba(321207ff)

$image = Null
$on_tertiary_fixed_variant = rgba(663c2eff)

$image = Null
$outline = rgba(9a8d95ff)

$image = Null
$outline_variant = rgba(4e444bff)

$image = Null
$primary = rgba(f2b3e5ff)

$image = Null
$primary_container = rgba(663560ff)

$image = Null
$primary_fixed = rgba(ffd7f4ff)

$image = Null
$primary_fixed_dim = rgba(f2b3e5ff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(dbbfd2ff)

$image = Null
$secondary_container = rgba(554050ff)

$image = Null
$secondary_fixed = rgba(f8daeeff)

$image = Null
$secondary_fixed_dim = rgba(dbbfd2ff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(997691ff)

$image = Null
$surface = rgba(171216ff)

$image = Null
$surface_bright = rgba(3e373cff)

$image = Null
$surface_container = rgba(241e22ff)

$image = Null
$surface_container_high = rgba(2f282dff)

$image = Null
$surface_container_highest = rgba(3a3337ff)

$image = Null
$surface_container_low = rgba(201a1eff)

$image = Null
$surface_container_lowest = rgba(120c11ff)

$image = Null
$surface_dim = rgba(171216ff)

$image = Null
$surface_tint = rgba(f2b3e5ff)

$image = Null
$surface_variant = rgba(4e444bff)

$image = Null
$tertiary = rgba(f5b8a6ff)

$image = Null
$tertiary_container = rgba(663c2eff)

$image = Null
$tertiary_fixed = rgba(ffdbd0ff)

$image = Null
$tertiary_fixed_dim = rgba(f5b8a6ff)

