cursor #e7e0eb
cursor_text_color #cbc3d5

foreground            #e7e0eb
background            #0f0d14
selection_foreground  #412742
selection_background  #e0bbdd
url_color             #85d7ae

# black
color8   #262626
color0   #4c4c4c

# red
color1   #E88594
color9   #E88594

# green
color2   #A3D393
color10  #A3D393

# yellow
color3   #E9CE9D
color11  #E9CE9D

# blue
color4  #85d7ae
color12 #85d7ae

# magenta
color5   #C3A0F3
color13  #C3A0F3

# cyan
color6   #81C2E1
color14  #81C2E1

# white
color15   #e7e7e7
color7  #f0f0f0
