cursor #dce4e9
cursor_text_color #bac9d1

foreground            #dce4e9
background            #080f13
selection_foreground  #362b4b
selection_background  #cfc0e8
url_color             #e4c461

# black
color0   #232b2f
color8   #2e363a

# red (secondary, hue forced to red)
color1   #da9b9b
color9   #432d2d

# green (tertiary, hue forced to green)
color2   #94e994
color10  #006300

# yellow (primary, hue forced to yellow)
color3   #e4e461
color11  #575700

# blue (primary, as-is)
color4   #e4c461
color12  #574500

# magenta (secondary, hue forced to magenta)
color5   #e8c0e8
color13  #624162

# cyan (tertiary, hue forced to cyan)
color6   #94e9e9
color14  #006363

# white
color7   #dce4e9
color15  #dce4e9

mark1_foreground #231a00
mark1_background #ffe087
mark2_foreground #201634
mark2_background #ebddff
mark3_foreground #001f2a
mark3_background #bce9ff

active_tab_foreground #3c2f00
active_tab_background #e4c461
inactive_tab_foreground #ffe087
inactive_tab_background #574500

active_border_color #e4c461
inactive_border_color #3c2f00
