cursor #f6decd
cursor_text_color #d9c2b2

foreground            #f6decd
background            #170c04
selection_foreground  #432c06
selection_background  #e7c08e
url_color             #ffb77b

# black
color0   #35271c
color8   #403226

# red (secondary, hue forced to red)
color1   #de6464
color9   #340f0f

# green (tertiary, hue forced to green)
color2   #77e377
color10  #015901

# yellow (primary, hue forced to yellow)
color3   #ffff7b
color11  #6d6d00

# blue (primary, as-is)
color4   #ffb77b
color12  #6d3a00

# magenta (secondary, hue forced to magenta)
color5   #e78ee7
color13  #5c1a5c

# cyan (tertiary, hue forced to cyan)
color6   #77e3e3
color14  #015959

# white
color7   #f6decd
color15  #f6decd

mark1_foreground #2e1500
mark1_background #ffdcc2
mark2_foreground #291800
mark2_background #ffddb3
mark3_foreground #251a00
mark3_background #ffdf95

active_tab_foreground #4d2700
active_tab_background #ffb77b
inactive_tab_foreground #ffdcc2
inactive_tab_background #6d3a00

active_border_color #ffb77b
inactive_border_color #4d2700
