[FileDialog]
history=file:///home/kuroma/Vault/songs/ALTIMA - Fight 4 Real, file:///home/kuroma, file:///home/kuroma/Vault/songs/\x4e16\x754c\x5f81\x670d - Neru feat. \x93e1\x97f3\x30ea\x30f3\x3001\x93e1\x97f3\x30ec\x30f3, file:///home/kuroma/Vault/songs/RSP - Sakura anata ni deatte yokatta, file:///home/kuroma/Vault/songs/Ariabl'eyeS Music Collection (2011-2019) [FLAC\xff0fWAV\xff0fMP3]/[ARS-036] Ariabl'eyeS - \x7d76\x51cd\x306e\x30e9\x30d3\x30ea\x30f3\x30b9 [M3-44] [FLAC], file:///home/kuroma/Vault/songs
lastVisited=file:///home/kuroma/Vault/songs/DECO\xff0a\x32\x37
qtVersion=5.15.18
shortcuts=file:, file:///home/kuroma
sidebarWidth=48
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5$\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2V\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\x2\"\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
