[FileDialog]
history=file:///home/kuroma/Vault/songs, file:///home/kuroma/Downloads, file:///home/kuroma, file:///home/kuroma/Vault/songs/KAMEN RIDER GEATS CD-BOX/KAMEN RIDER GEATS TV ORIGINAL SOUNDTRACK, file:///home/kuroma/Vault/songs/KAMEN RIDER GEATS CD-BOX/KAMEN RIDER GEATS SONG BEST
lastVisited=file:///home/kuroma/Vault/songs
qtVersion=5.15.18
shortcuts=file:, file:///home/kuroma
sidebarWidth=48
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5$\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2V\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\x2\"\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
